baseurl = "https://harakaza.tech/"
languageCode = "en"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Hara Kaza"
    subtitle = "Another personal blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Hara Kaza"
      logoHomeLink = "/"
	  
	[languages.en.menu]
      [[languages.en.menu.main]]
		identifier = "DoL"
        name = "Degrees of Lewdity"
        url = "/DoL/Degrees-of-Lewdity.html/"
      [[languages.en.menu.main]]
        identifier = "theme"
        name = "theme"
        url = "/theme"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
